security:
    providers:
        app_user_provider:
            entity:
                class: App\Security\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/api
            anonymous: true
            stateless: true
            guard:
                authenticators:
                    - App\Security\JwtAuthenticator

        main:
            anonymous: true

    access_control:
        - { path: ^/api/validate, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: ROLE_STAFF }

